### PR TITLE
Deprecate `lzf`, `rar` and `snappy` compression adapters

### LINKED ISSUE #79: [RFC]: Deprecate Compression Adapters Lzf, Rar and Snappy
## RFC

| Q                   | A      |
| ------------------- | ------ |
| Proposed Version(s) | 2.x.   |
| BC Break?           | Not yet |

Further to https://github.com/laminas/laminas-filter/pull/78

Rar, Lzf and Snappy all need extra work to get their respective custom extensions installed.

Propose to deprecate these adapters in a forthcoming minor release of the 2.x series for removal in 3.0 in order to reduce maintenance burden of _probably_ infrequently used adapters.

### PR DESCRIPTION
**Pull request by gsteel**
Closes #79

### CODE REVIEW

**Review by Ocramius — APPROVED** [review]

**Comment by Ocramius** [comment]
Thanks @gsteel - please also create an issue (or PR) for removal for `3.0.0`, so we don't forget :+1:

**Comment by froschdesign** [comment]
@Ocramius 
The syntax for the deprecation messages are wrong. But I didn't have a chance to finish my review. :disappointed:

**Comment by froschdesign** [comment]
@gsteel 
See:

https://github.com/laminas/laminas-filter/blob/c038ae257028b57b1f96df0d4ccb68cfc04eaa40/docs/book/standard-filters.md?plain=1#L158-L160

**Comment by gsteel** [comment]
Sorry @froschdesign - Thanks for pointing out where I can get it right :) - I'll send in another PR shortly

**Comment by Ocramius** [comment]
Ah, sorry :|

**Pull request merged**
