### PR TITLE
Apply PHP 8.0 Syntax and constructor promotion

### PR DESCRIPTION
**Pull request by samsonasik**
Signed-off-by: Abdul Malik Ikhsan <samsonasik@gmail.com>

|    Q          |   A
|-------------- | ------
| QA            | yes

### Description

Since composer.json require php 8.0, php 8.0 syntax can constuctor promotion can be applied.

### CODE REVIEW

**Review by Ocramius — APPROVED** [review]
Thanks @samsonasik!

**Comment by Ocramius** [comment]
Ah, the compress filter patches are pending #78, IMO

**Comment by Ocramius** [comment]
@samsonasik a rebase should help here :+1:

**Comment by samsonasik** [comment]
@Ocramius rebased.

**Comment by samsonasik** [comment]
@Ocramius All green 🎉

**Review by Ocramius — APPROVED** [review]
Thanks @samsonasik!

**Pull request merged**
