### PR TITLE
Deprecated crypto filter test removal

### PR DESCRIPTION
**Pull request by gsteel**
### Description

Removes tests for deprecated filters and their adapters:

- Encrypt
- Decrypt
- File\Encrypt
- File\Decrypt

The removed tests are failing CI in a way that cannot be fixed because certain OpenSSL features used in `laminas-crypt` are no longer supported in OpenSSL 3+

Related: https://github.com/laminas/laminas-crypt/pull/26

Also fixes some missed dynamic property assignments and replaces a missed `utf8_encode` call.

Closes #90

### CODE REVIEW

**Comment by gsteel** [comment]
🤷‍♂️ Now the matrix isn't kicking off! Any ideas @Ocramius??

**Comment by Ocramius** [comment]
No idea 🤔

**Comment by Ocramius** [comment]
```
Matrix: [
  {
    "name": "No checks",
    "operatingSystem": "ubuntu-latest",
    "action": "laminas/laminas-continuous-integration-action@v1",
    "job": {
      "command": "",
      "php": "7.4",
      "extensions": [],
      "ini": [],
      "dependencies": "locked",
      "ignore_platform_reqs_8": false,
      "ignore_php_platform_requirement": false,
      "additional_composer_arguments": [],
      "before_script": []
    }
  }
]
```

Wth 🤔

**Comment by gsteel** [comment]
Also, why is 7.4 the default stable?

**Comment by Ocramius** [comment]
@internalsystemerror would you perhaps have an idea of how to investigate this?

**Comment by internalsystemerror** [comment]
I had something happen once before some time ago where it gave back no checks to be ran. It seemed to be thinking there were no changes in git and when I tried to investigate, it disappeared almost as quickly as it appeared and I was unable to replicate it. Could it be just a temporary network glitch or something like that? ~~It could be that it just needed retriggering.~~ (edit: unlikely if you were able to get this to repeat)

**Comment by gsteel** [comment]
I just sent in a patch to the matrix to change stable PHP: https://github.com/laminas/laminas-ci-matrix-action/pull/163

No CI ran there either - perhaps this is a GutHub issue?

**Comment by gsteel** [comment]
FWIW, I also ran the matrix container locally on _this_ PR and it spat out all the expected jobs

**Comment by gsteel** [comment]
OK - for extra weirdness, CI is running successfully on my fork:
https://github.com/gsteel/laminas-filter/actions/runs/3731690958

**Comment by gsteel** [comment]
Did someone forget to pay the GHA bill 😅

**Comment by internalsystemerror** [comment]
Yep, I'm getting the same works fine locally ... Aside from caching, the only thing I can think of is:

```
Switched to branch 'pull/deprecated-crypto-filter-test-removal'
Preparing file diff
Found changes in the following files:
composer.json
composer.lock
psalm-baseline.xml
src/UriNormalize.php
test/DecryptTest.php
test/Encrypt/BlockCipherTest.php
test/Encrypt/OpensslTest.php
test/Encrypt/openssl/private_encrypted_[20](https://github.com/laminas/laminas-filter/actions/runs/3731691570/jobs/6330203754#step:3:21)48.pem
test/Encrypt/openssl/private_encrypted_[40](https://github.com/laminas/laminas-filter/actions/runs/3731691570/jobs/6330203754#step:3:41)96.pem
test/Encrypt/openssl/private_unencrypted_2048.pem
test/Encrypt/openssl/private_unencrypted_4096.pem
test/Encrypt/openssl/public_2048.pem
test/Encrypt/openssl/public_4096.pem
test/EncryptTest.php
test/File/DecryptTest.php
test/File/EncryptTest.php
test/FilterPluginManagerCompatibilityTest.php
test/InflectorTest.php
test/StringTrimTest.php
test/_files/encryption.txt
test/_files/privatekey.pem
test/_files/privatekey_pass.pem
test/_files/publickey.pem
test/_files/publickey_pass.pem
Performing selective checks based on pull request patch diff
Running code checks: No
Running doc linting: No
```

Is it the pull request patch diff which is empty? Does that differ from the file diff? (is it this which is being cached?)

**Comment by Ocramius** [comment]
I also tried a re-run 🤷‍♀️

**Comment by gsteel** [comment]
@internalsystemerror Not sure what you mean about the patch vs files diff - lots of files and file contents have changed - I can't see how a diff could be empty here??

Also, there are zero caches in Actions Cache for this repo. Are you talking about docker caches? even if those were out of date, we still shouldn't have a broken matrix right?

**Comment by internalsystemerror** [comment]
Im just referring to the logs, it starts with "file diff" and lists all the changes, and then at the bottom says "performing checks based on pull request patch diff", I'm not sure what the difference between those is either.

Which caches am I talking about? Any, I don't know what caches there are in the way here, just a thought.

**Comment by internalsystemerror** [comment]
It's definitely running the correct container too:


| Version | Digest |
| --- | --- |
| Expected (1.21.0) | d3e218d68be1d9a85603cea77810dff92715746f6ee68868a0857b0134ecd270 |
| Actual (1.21.0) | d3e218d68be1d9a85603cea77810dff92715746f6ee68868a0857b0134ecd270 |

**Pull request closed without merging**
