### PR TITLE
Remove deprecated filters

### LINKED ISSUE #82: Remove Deprecated Compression Adapters
|    Q        |   A
|------------ | ------
| BC Break    | yes

#### Summary

`lzf`, `snappy` and `rar` compression adapters are deprecated and require removal in 3.0

- [x] Remove Adapters & Tests
- [x] Remove `pre-install.sh`
- [x] Update documentation

### LINKED ISSUE #84: Remove Deprecated Encryption & Decryption Filters
|    Q        |   A
|------------ | ------
| BC Break    | yes

#### Summary

The `Encrypt` and `Decrypt` filters are deprecated for removal in 3.0

- [x] Remove Filters and relevant tests
- [x] Remove Relevant Adapters, Adapter Interface and tests _(i.e. `BlockCipher` and `OpenSSL`)_

### PR DESCRIPTION
**Pull request by gsteel**
Removes the deprecated filters:

- Compression Adapters for Lzf, Snappy and Rar
- Encryption and Decryption related filters
- Blacklist and Whitelist
- StaticFilter

Cut from #101, so this will need a rebase and a 3.0 branch once that's merged.

Removing the dev dependency on laminas-crypt clears the way for testing this lib on laminas-servicemanger 4.x

- Closes #84 
- Closes #82

### CODE REVIEW

**Comment by froschdesign** [comment]
If features are removed then this must be documented in a migration guide.

```yaml
- Migration:
  - "Migration from Version 2 to 3": v3/migration/v2-to-v3.md
```

Example: https://docs.laminas.dev/laminas-form/v3/migration/v2-to-v3/

**Comment by gsteel** [comment]
@froschdesign 

Is it best to revert docs changes here and move them to a `v2` subdirectory, duplicate `v2` to `v3` and make changes in the `v3` tree, adding a migration guide? (In a separate PR)

**Comment by froschdesign** [comment]
@gsteel You are right, a revert and a separate pull request is the correct way.

**Comment by gsteel** [comment]
Any chance of an approval on this one? Everything is green 🙏

**Review by samsonasik — APPROVED** [review]

**Comment by gsteel** [comment]
Thanks @samsonasik

**Comment by nishant04412** [comment]
@gsteel Since `laminas/laminas-crypt` is abandoned completely but not removed from `2.39.x` or any `2.x.x` version so when can we expect `3.0.x` version to be released or can we raise PR to backport this removal of `laminas/laminas-crypt` from `2.x.x` version ? Please suggest.

**Comment by gsteel** [comment]
3.0 will be released when it's ready. There is no forecasted date. All the crypt related filters are still available in 2.x and cannot be removed from 2.x because that would be a BC break - this is why they have been removed from 3.x only

**Pull request merged**
